### ISSUE TITLE
Solix Sensors not refreshing

### ISSUE THREAD

**Issue by markusruebe** [tomquist/solix2mqtt#4]
Hi all,

I just installed the Solix 2 Mqtt Add On to my HA instance. The sensors are there but they do not update. 
MQTT data is sent to eh broker - interval is set to 60.

Any idea what I could do?

As you see in the screenshots no update since 36 min.
The Anker App on my iPhone is closed.

<img width="555" alt="Bildschirmfoto 2024-02-06 um 12 53 16" src="https://github.com/tomquist/solix2mqtt/assets/53835421/c1133965-d7cb-459c-894b-164a70482d89">
<img width="371" alt="Bildschirmfoto 2024-02-06 um 12 53 00" src="https://github.com/tomquist/solix2mqtt/assets/53835421/294a196e-39fa-406a-b9e8-fb884e283557">
<img width="473" alt="Bildschirmfoto 2024-02-06 um 12 52 52" src="https://github.com/tomquist/solix2mqtt/assets/53835421/090f82eb-fc5c-4bc6-8b15-b06c8f975eb9">

Here the entry from MQTT Explorer:

<img width="387" alt="Bildschirmfoto 2024-02-06 um 12 56 20" src="https://github.com/tomquist/solix2mqtt/assets/53835421/4da8d38d-c9ee-4788-9103-f3dcc36be599">

**Comment by tomquist** [comment]
Could you please provide some logs? You can enable verbose logging by setting the env var `S2M_VERBOSE` to true.

**Comment by markusruebe** [comment]
Hi Tom, could you please give me advise "where / how" to enable the verbose logging? Thanks!

**Comment by tomquist** [comment]
How are you running the script?

**Comment by markusruebe** [comment]
<img width="1049" alt="Bildschirmfoto 2024-02-06 um 14 18 08" src="https://github.com/tomquist/solix2mqtt/assets/53835421/83d43a3b-73c8-4ddd-bc13-8fa4f1d1de0c">

I installed the Add On to my HA instance. Nothing changed in configuration.yaml etc.

**Comment by markusruebe** [comment]
That is what I found in HA log:

`2024-02-06 12:47:44.518 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'TRUE' is undefined when rendering '{{ states('sensor.netatmo_basis_windmesser_angle') | regex_findall_index('([0-9]+)',index=0,ignorecase=TRUE)  }}'
2024-02-06 12:47:44.519 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'TRUE' is undefined when rendering '{{ states('sensor.netatmo_basis_windmesser_angle') | regex_findall_index('([0-9]+)',index=0,ignorecase=TRUE)  }}'
2024-02-06 12:47:44.539 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states('sensor.batterie_leistung') | float * (1 / 1000) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1984, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 567, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2305, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1987, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1625, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states('sensor.batterie_leistung') | float * (1 / 1000) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 693, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states('sensor.batterie_leistung') | float * (1 / 1000) }}' but no default was specified
2024-02-06 12:47:44.555 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states('sensor.batterie_leistung') | float * (1 / 1000) }}' but no default was specified') while processing template 'Template<template=({{ states('sensor.batterie_leistung') | float * (1 / 1000) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.batterie_verbrauch'
`

**Comment by tomquist** [comment]
Ah I see. The Home Assistant Add-On was not published by me so unfortunately I can’t provide support for it. It just happens to use this library.

**Comment by markusruebe** [comment]
ah - ok - how could I use your library without the add on? install it in the HA terminal?

**Comment by tomquist** [comment]
I‘m not a HA user so I’m not sure what is the best way to run it. I provided a couple of options in the README file how to run the scrip on general.

The latest logs indeed are the logs from this script but they look fine to me. Based on these the last event was published on 2024-02-06T13:23:02 UTC.
